# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bbf6992f3cee7aab5a5fa610caca666daf309dc88745aa48cf626aa5090c3eff2a41e0e6368234989547e9d2d2aa8e897ce59dae392cc6cc0f95f5fa9a36c4e

test:
  secret_key_base: 3874604e488abb1ec3262653ec8cd6b8212141996b3536602e0bb611ab796e791d47a38cb181860e5b084a517d9de2cfaaf954524287a222bacf4a96228d65d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
